### ISSUE TITLE
Feature request: option to adjust swarm z index or play above tokens

### ISSUE THREAD

**Issue by MrPotatoZed** [oOve/swarm#1]
Currently swarms only appear to show up below tokens even when the z index of the "control token" is increased (in my case using token z). Trying to create a swarm of flying creatures and it would be great if they played above tokens or if we had the option to select whether particular swarms would appear above or below tokens. I'd think that in most cases we'd want the swarming creatures to crawl on top of other creatures but there might be other opinions on that or situations where particular swarms of bugs or whatnot should appear below other stuff. 

Thanks for all your work on this. Now all I need to do is figure out how to get a swarm to be briefly summoned on top of a target token as the "animation" for my swarmkeeper ranger's gathered swarm ability or for spells like insect plague.

**Comment by oOve** [comment]
Added, will feature in next release. Added a flag next to "is swarm" with "over".
If over, they will be in the foreground layer, if not, background layer. (i.e., over under tokens.)
Will close when release is live

**Comment by MrPotatoZed** [comment]
Awesome; thank you!

**Comment by oOve** [comment]
Fixed in v.9.0.2
