### ISSUE TITLE
Bug: Main Token Image Still Visible

### ISSUE THREAD

**Issue by Crowguard** [oOve/swarm#10]
~~Tried on newly created and old tokens.~~

~~Edit: I see the spiders in the demonstration GIF still has the token, but the rats don't?~~

Figured it out; adjusting the token opacity.

https://user-images.githubusercontent.com/99844555/185015372-1cc16caa-5ec9-4008-b018-4e9312ee67e0.mp4

Foundry 9.269
D&D 5e 1.6.3

**Comment by gsterling** [comment]
Should be the same as #3 

Or do you still see it as non-GM?

**Comment by oOve** [comment]
If it is, i should put a note about it in the faq :)

**Comment by Shuggaloaf** [comment]
@oOve Figured I'd comment here since the other thread was closed. Even though it's only shown for the DM, any chance that will be addressed in the future? 

I know the players can't see it, but I want to see the cool swarm without main token too! ;)

**Comment by Crowguard** [comment]
> Should be the same as #3
> 
> Or do you still see it as non-GM?

Nope; it isn't visible as a player regardless of token transparency.

Lowering the token transparency to 0 hides it for the GM while leaving the swarm visible for everyone, it should probably get added to the faq 😄

**Comment by oOve** [comment]
Ok, I'll add it to the doc. closing this issue
