### ISSUE TITLE
[Feature Request] Swarm Shape

### ISSUE THREAD

**Issue by Shuggaloaf** [oOve/swarm#11]
Would it be possible to give the swarm a more circular bounding area rather than the square one it has now? Even on hexgrid it's still a square shape.

Having it be an option would be fine, as I could see some users wanting it to conform to the grid square. Allowing a circular option though would give a much more realistic look.

**Comment by oOve** [comment]
I hadn't even thought about hex grids. Yes, I'ts possible to make the shape more circular. Good idea, maybe even as default for hexgrids.
Though, that opens another questions, in grids you can set size in X and Y, how is this handled in hex? experiments needed :)

**Comment by oOve** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/8543541/185266384-722eb065-542a-4bc5-9f3a-e749b31c08b9.png)

**Comment by oOve** [comment]
Or here, actually shown on a hex grid: 
![image](https://user-images.githubusercontent.com/8543541/185266879-847bc311-134f-461b-9b95-e71ba6eb5297.png)

**Comment by Shuggaloaf** [comment]
I think that looks pretty good. And to be honest, I don't use hex grids, I had just switched it to hex to see if the bounding shape got altered. It looks like you have it circularized in square grid as well though so that's perfect. 

I think it looks pretty good! I really noticed the box shape when testing a hundred or so little spiders, I think that will be the real test. Looking forward to testing it out in 9.0.3!

Thanks for taking the suggesting and getting it implemented so quickly!

**Comment by oOve** [comment]
Implemented and live as of 9.0.3

**Comment by Shuggaloaf** [comment]
Nice! Will update shortly. Thanks Doc!
