### ISSUE TITLE
Feature Request: Support for Animated Tokens

### ISSUE THREAD

**Issue by Dumbhuman** [oOve/swarm#12]
Ok, I spoke too soon when I said the module had everything I wanted.  I did a little animated test of a tiny rot grub this morning before seeing that the swarm images stayed static.  
![RotGrubs](https://user-images.githubusercontent.com/63615591/185679425-77b13a43-3abf-4f10-a377-9c2e47c87bf0.gif)

It's not an absolute need of course, because static images can be lots of fun too especially if some faked movement is baked in.
![Beeholder20](https://user-images.githubusercontent.com/63615591/185688261-2a8231a3-09a5-4b3a-bf6e-b90a391476be.gif)

I'm just thinking about editing/expanding my token art for swarms and before I dive into doing anything I figured I'd ask if animated tokens were a possible addition.

**Comment by oOve** [comment]
An excellent idea :)
I just need to see how much work it takes.

**Comment by oOve** [comment]
ps, I'm loving your assets. What are they from?

**Comment by oOve** [comment]
That wasn't overly hard. Will be live in the next release.

![SilkySlimFeline-size_restricted](https://user-images.githubusercontent.com/8543541/185767938-a6a6caf7-950e-470a-a420-1b90f547ced9.gif)

**Comment by Dumbhuman** [comment]
Awesome!  I'll probably have time to start playing with it on Monday.  I draw my own assets and sell tokens on Roll20's Marketplace plus The Forge's Bazaar under the name DumbHumanDrawn, but if you're looking to bundle some stuff with this module, I'll happily hand over some tiny little swarm builders once I've built up a little more variety of them.

**Comment by oOve** [comment]
I'd gladly include some in a 5e compendium. V10 does not allow system agnostic actor compendiums, so we have to make them for specific systems. 
E.g., an srd swarm or two :)

**Comment by oOve** [comment]
Fix live in release https://github.com/oOve/swarm/releases/tag/9.0.4

**Comment by Shuggaloaf** [comment]
@Dumbhuman Just wanted to say the "beeholder" is pretty funny. :)

Also, regarding this: _"I'll happily hand over some tiny little swarm builders once I've built up a little more variety of them."_
That is amazing that you're planning to share in the future. Thanks in advance!
