### ISSUE TITLE
Support for S3-hosted images

### ISSUE THREAD

**Issue by MrZwij** [oOve/swarm#13]
Please add support for images hosted in S3.

When I use an image hosted there, I only get the central image, no swarm.

![image](https://user-images.githubusercontent.com/12764695/185807926-2c506b01-df84-47fc-80e1-eaf4ffd5afa9.png)

p.s. Never knew I need this module so badly. :D Thanks for making it, it's awesome!

**Comment by oOve** [comment]
Fix featured in next release

**Comment by oOve** [comment]
Fix live in release https://github.com/oOve/swarm/releases/tag/9.0.4
