### ISSUE TITLE
Unexpected behavior when hiding tokens

### ISSUE THREAD

**Issue by MrZwij** [oOve/swarm#15]
Unfortunately I don't have time to dig into this because my game is in 1 hour. But what I've noticed while logged in at the same time as both GM and player is:

**Hiding the token**
- GM's swarm disappears and is replaced by single center image. Desired behavior: Swarm still visible at lower transparency.
- Player's swarm does not disappear. Desired behavior: Swarm disappears.
- Note: If the player refreshes, the swarm does disappear

**Player joins map where token is already hidden**
- Token (and swarm) are not visible (correct behavior)
- If the token is then revealed, the center token is visible, but not the swarm. This can be fixed by refresh by player, or GM deleting/undo deleting token.

Note: I have a *lot* of other modules. I can try and Find the Culprit this if needed when I have more time.

**Comment by oOve** [comment]
Bug on my side. Fix featuring in next release.

**Comment by oOve** [comment]
Will leave the complete removal of swarm on DM's client as well for now. Will query the popularity of this on my discord.

**Comment by oOve** [comment]
Release live, https://github.com/oOve/swarm/releases/tag/9.0.4
