### ISSUE TITLE
Compatibility issue with V10 version

### ISSUE THREAD

**Issue by drewg13** [oOve/swarm#19]
So the effect of the issue is that your 10.0.1 version is still being served up as an update for V9 and I suspect that's not what you intended.  The reason is that your `module.json` file still contains a v9-compatible `name` field, but no longer contains any V9-compatible compatibility fields (V9 does not parse the new `compatibility` object and ignores it).  Because of that, V9 Foundry assumes that all versions are compatible and serves it up as an update.  If your intent was to make your version 10.0.1 only available for V10, you need to either:

remove the `name` field completely, so that V9 does not see a valid manifest for this and future versions

OR

add `minimumCoreVersion: 10`, so that V9 knows that this is not a V9-compatible version

But not both.

You can actually do this just by editing your current `module.json`, you shouldn't have to make a new release or anything and it should work the way you intended from then on.

**Comment by oOve** [comment]
Thank you for pointing this out. I guess I have overestimated the version control I can set at the admin panel at foundry's site. I have updated the v10.0.1 manifest with your suggested change.

**Comment by drewg13** [comment]
No problem, thanks for the cool module.  I love using it for all the bug swarms.  Great stuff!
