### ISSUE TITLE
Bug: Prototype token swarms fly away when token placed

### ISSUE THREAD

**Issue by MrPotatoZed** [oOve/swarm#2]
Changing an existing token on a scene into a swarm seems to work as expected. However, if the prototype token of an actor is changed into a swarm and then the actor is dragged onto a scene the swarm images all make a beeline for the top left corner of the scene and eventually bounce away when they hit the corner. See attached video.

v9.269, 5e 1.6.3, swarms 9.0.1, hosted on the forge. Same behavior in firefox and chrome. Tested with only swarms active. No errors in console.
![swarms](https://user-images.githubusercontent.com/85974617/184809622-b4e1de31-8d7d-492d-a327-aa3e50c01f21.gif)

**Comment by GregsGrog** [comment]
Can confirm am able to reproduce this issue. Also on forge and also with no other modules installed.

**Comment by oOve** [comment]
Early release is buggy 🐛  :D  be warned.
Jokes aside, will fix for next release.

**Comment by oOve** [comment]
Fixed in v.9.0.2
