### ISSUE TITLE
Placing tokens

### ISSUE THREAD

**Issue by Ikabodo** [oOve/swarm#21]
Thank you for a really cool mod!

When you place tokens on a map the swarm spawns in the upper left corner, causing the swarm to slowly move towards the token. You can either wait for the swarm to travel, or deactivate and reactivate the swarm to make it appear where the token is.

It would make more sense if the swarm spawned where the token is placed. 

Sidenote: It would make sense have two speed settings, one for idle and one for moving. Especially for larger swarms.

**Comment by Crowguard** [comment]
Just confirming and adding an example video. 

https://user-images.githubusercontent.com/99844555/195769062-72c9c634-984c-4dc8-8761-be4c23900955.mp4

Foundry 10.288
Swarms 10.0.2

**Comment by oOve** [comment]
I had this bug fixed in V9 :D
Guess it needs another whack to work properly again.

**Comment by oOve** [comment]
Should be fixed as of 10.0.3
