### ISSUE TITLE
Bug: When moving a swarm per drag and drop around the map it's main token becomes visible again

### ISSUE THREAD

**Issue by gsterling** [oOve/swarm#3]
I placed two swarms on the ground and moved the right one. It started showing the original token in it's center. I tested it with all other modules deactivated.

![image](https://user-images.githubusercontent.com/58980630/184890831-ff9f3355-61f5-4418-96c5-8071ccf6c661.png)

Only when using the arrow keys to move the token it stays as expected.

**Comment by oOve** [comment]
The "control token" will only be visible on the DMs client AFAIK. 
If this is not the case, let me know.

**Comment by Shuggaloaf** [comment]
>only visible on the DMs client 

Noticed the same issue and I just tested by logging in as a player. I can confirm only the DM sees.

**Comment by oOve** [comment]
The control token will remain visible as DM, should be invisible on players screens. Will close this issue.
