### ISSUE TITLE
Bug: Miniature tokens move backwards

### ISSUE THREAD

**Issue by gsterling** [oOve/swarm#4]
My miniature tokens are crawling backwards in a swarm.

They have a downward orientation, as it is default for foundry. Otherwise the normal tokens wouldn't look in the right direction, when rotating. Excerpt from the FoundryVTT docs:
> Rotation of zero (the default) corresponds to a southward facing as this is the most commonly used convention for Token artwork.

See: https://foundryvtt.com/article/tokens/

So the swarm's mini tokens' orientation should be rotated by 180° and it should be default. You could add a additional toggle or field for a custom orientation in the options.

**Comment by oOve** [comment]
Thank you for refering to the docs. I'll swap the direction for tonights release.

**Comment by oOve** [comment]
Fixed in v.9.0.2
