### ISSUE TITLE
Bug: Aspect ratio of mini tokens changes when copy and pasting newly created swarm

### ISSUE THREAD

**Issue by gsterling** [oOve/swarm#7]
When using tokens, that don't have a 1:1 aspect ratio the swarm could be created with the wrong aspect ratio.

I use horses with 1:2 (e.g. 500px wide, 1000px tall) aspect ratio as the token picture (but not as the token aspect ratio. That's a 1x1 still).

1) Place the new horse token
2) Edit it to create a swarm
3) Copy the token and place it next to the original
4) Copy it again and place it again

![image](https://user-images.githubusercontent.com/58980630/184897941-bebd0408-fc64-4351-a065-80966b78dc54.png)
As you see, the left token isn't updated as described in #5, but the new one in the middle has a wrong aspect ratio. The second time the token get's copied on the right it keeps the correct ratio. This is reproducible by me, it's always the first copy.

**Comment by oOve** [comment]
This took longer than I'd like to admit. But finally got it sorted. 
Will feature in the next release

**Comment by oOve** [comment]
Fixed and live as of 9.0.3
