### ISSUE TITLE
Feature Request: Use Images from Alternate Actor Tokens if Available

### ISSUE THREAD

**Issue by Dumbhuman** [oOve/swarm#8]
First off, thank you for this module, because it looks like it's got the potential to be tons of fun!  

Others already touched on my top issues: getting updates to work on the token without refreshing the page, an option to have the swarm display over tokens (especially the control token), an option to customize scaling/speed, an option to change the default orientation of the token (I draw my tokens south-facing too), etc.

One thing I didn't see mentioned yet though was the option to use wildcard token images.  I'd love to be able to add some variety into the swarms.  Pulling images from Alternate Actor Tokens should scratch that itch nicely if it's possible to implement.

![image](https://user-images.githubusercontent.com/63615591/184948967-18632590-e175-424c-9c0b-bc76c97385d0.png)

**Comment by oOve** [comment]
Those are some cool assets. I'll have to do some investigation into the internal workflow on how Foundry handles wildcard tokens.
I know that they only exist in the prototype token. So far I only handle tokens, and at that stage I fear its too late to extract wildcard information. Anyway, its now officially on my list, and I will get around to it, ... soon :)

**Comment by oOve** [comment]
Next release will support wildcard tokens.
![image](https://user-images.githubusercontent.com/8543541/185268783-17aa548a-4866-4e1b-8ad2-dfd7eceb5263.png)

**Comment by Dumbhuman** [comment]
Looking great!  I think the only other suggestion I might have at this point is being able to scale the swarming images independently from the control token image, but that's mostly because I'd like the control token to not be so obviously different.  However I'll be able to use this wildcard feature to get that effect by using a transparent token for the main token so that I can't even see it!

**Comment by oOve** [comment]
If you lower the transparency on the Appearance tab, you can make the control token almost invisible, while still seeing the swarm.

**Comment by oOve** [comment]
Implemented and live as of 9.0.3

**Comment by Dumbhuman** [comment]
Just a got chance to check out the update and it's awesome!  It also seems like the scale matches that of the original token, which works great for my needs!
![SwarmingSpidersOnKobold](https://user-images.githubusercontent.com/63615591/185513907-5adbc613-9086-4000-ad76-3cec54e2173c.gif)

Now I've just got to carve out some time to repurpose some of my static swarm token stuff into these super fun ones!
